<!--
  ========================================================================
  Copyright © 2026 Blue Wolf Enterprises LLC
  Author: ThomasM. Testi
  Created: 2026-02-04
  All rights reserved.
 ========================================================================
-->

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	  <Title>Authentication Library</Title>
	  <PackageId>BlueWolf.AuthLibraryTMT</PackageId>
	  <Authors>Thomas M Testi</Authors>
	  <Company> Blue Wolf Enterprises LLC.</Company>
	  <Description>This package includes common permission based authentication</Description>
	  <SignAssembly>true</SignAssembly>
	  <PackageProjectUrl>https://bluewolfenterprisesllc.com/</PackageProjectUrl>
	  <PackageRequiredLicenseAcceptance>true</PackageRequiredLicenseAcceptance>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="10.0.2" />
  </ItemGroup>

</Project>
